# Site wide configuration

title:            alykhantejani.com
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Alykhan Tejani
  avatar: bio-photo.jpg
  bio: "Hi! My name is Aly. I'm currently a senior research engineer at <a class='author-bio-link' href='http://www.blippar.com'>Blippar</a>. Prior to this I was doing computer vision research at <a class='author-bio-link' href = 'http://www.iis.ee.ic.ac.uk/ComputerVision/index.html'> Imperial College</a> and before this, a software engineer at Goldman Sachs. So in short, I'm a geek. Check out the <a class='author-bio-link' href = '/about'>about</a> page for more information."
  email: 
  disqus-shortname: 
  twitter: alykhantejani
  facebook: #username
  google:
    plus: AlykhanTejani
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: alykhantejani
  stackoverflow: http://stackoverflow.com/users/225814/aly
  linkedin: alykhantejani
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
